[package]
name = "sel4cp-message"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
cfg-if = "1.0.0"
num_enum = { version = "0.5.9", default-features = false }
sel4cp = { path = ".." }
zerocopy = "0.6.1"
