[package]
name = "sel4-full-root-task-runtime"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = ["sel4-panicking/alloc", "sel4-backtrace/alloc"]
allow-panic-unwind = ["sel4-panicking/allow-panic-unwind"]
full = ["full-less-alloc", "alloc", "global-allocator"]
full-less-alloc = ["postcard", "unwinding", "allow-panic-unwind"]
global-allocator = []
postcard = ["sel4-backtrace/postcard"]
unwinding = ["sel4-panicking/unwinding", "sel4-backtrace/unwinding"]

[dependencies]
sel4 = { path = "../../sel4" }
sel4-backtrace = { path = "../sel4-backtrace" }
sel4-dlmalloc = { path = "../sel4-dlmalloc" }
sel4-full-root-task-runtime-macros = { path = "./macros" }
sel4-panicking = { path = "../sel4-panicking" }
sel4-runtime-building-blocks-abort = { path = "../sel4-runtime-building-blocks/abort" }
sel4-runtime-building-blocks-elf = { path = "../sel4-runtime-building-blocks/elf" }
sel4-runtime-building-blocks-termination = { path = "../sel4-runtime-building-blocks/termination" }
sel4-sync = { path = "../sel4-sync" }

[dependencies.sel4-runtime-building-blocks-injected-phdrs]
path = "../sel4-runtime-building-blocks/injected-phdrs"

[dependencies.sel4-runtime-building-blocks-reserve-tls-on-stack]
path = "../sel4-runtime-building-blocks/reserve-tls-on-stack"

[dependencies.sel4-runtime-building-blocks-root-task-head]
path = "../sel4-runtime-building-blocks/root-task-head"

[dependencies.sel4-runtime-building-blocks-unwinding-support]
path = "../sel4-runtime-building-blocks/unwinding-support"
