[package]
name = "sel4-full-root-task-runtime"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = ["sel4-panicking/alloc"]
full = ["full-less-alloc", "alloc", "global-allocator"]
full-less-alloc = ["unwinding"]
global-allocator = ["sel4-runtime-simple-static-heap"]
unwinding = ["sel4-panicking/unwinding"]

[dependencies]
sel4 = { path = "../../sel4" }
sel4-full-root-task-runtime-macros = { path = "./macros" }
sel4-panicking = { path = "../sel4-panicking" }
sel4-panicking-env = { path = "../sel4-panicking/env" }
sel4-reserve-tls-on-stack = { path = "../sel4-reserve-tls-on-stack" }
sel4-runtime-simple-entry = { path = "../sel4-runtime-simple-entry" }
sel4-runtime-simple-static-heap = { path = "../sel4-runtime-simple-static-heap", optional = true }
sel4-runtime-simple-termination = { path = "../sel4-runtime-simple-termination" }

[dependencies.sel4-runtime-phdrs]
path = "../sel4-runtime-phdrs"
features = ["unwinding", "tls", "embedded-phdrs"]
