[package]
name = "sel4-bitfield-parser"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
pest = "*"
pest_derive = "*"
regex = "*"
