[package]
name = "capdl-embed-spec"
version = "0.1.0"
edition = "2021"

[dependencies]
capdl-types = { path = "../types", features = ["alloc"] }
hex = "*"
miniz_oxide = "0.6.2"
proc-macro2 = "1"
quote = "1"
serde = "*"
serde_json = "*"
syn = "1"
