[package]
name = "sel4-externally-shared"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
alloc = []
unstable = []
very_unstable = ["unstable"]

[dev-dependencies]
rand = "0.8.3"
