[package]
name = "sel4-runtime-building-blocks-unwinding-support"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
sel4-runtime-building-blocks-elf = { path = "../elf" }
unwinding = { git = "https://github.com/nspin/unwinding.git", rev = "75c9607b61418e49cb5059eabb782c13c3ae4b6b", default-features = false, features = ["unwinder", "fde-custom", "hide-trace"] }
