[package]
name = "capdl-initializer-with-embedded-spec-embedded-spec"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
deflate = ["capdl-initializer-types/deflate"]

[dependencies]
capdl-initializer-types = { path = "../../types", features = ["borrowed-indirect"] }

[build-dependencies]
capdl-initializer-embed-spec = { path = "../../embed-spec" }
capdl-initializer-types = { path = "../../types" }
capdl-initializer-with-embedded-spec-build-env = { path = "../build-env" }
sel4-rustfmt-helper = { path = "../../../sel4-rustfmt-helper" }
serde_json = "1.0.87"
