[package]
name = "sel4cp"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = ["sel4-panicking/alloc"]
default = ["unwinding"]
full = ["default", "global-allocator"]
global-allocator = ["alloc", "sel4-runtime-simple-static-heap"]
single-threaded = ["sel4/single-threaded"]
unwinding = ["sel4-panicking/unwinding"]

[dependencies]
sel4 = { path = "../sel4", features = ["single-threaded"] }
sel4-panicking = { path = "../runtime/sel4-panicking" }
sel4-panicking-env = { path = "../runtime/sel4-panicking/env" }
sel4-runtime-simple-entry = { path = "../runtime/sel4-runtime-simple-entry" }
sel4cp-macros = { path = "./macros" }

[dependencies.sel4-runtime-phdrs]
path = "../runtime/sel4-runtime-phdrs"
features = ["unwinding", "tls", "embedded-phdrs"]

[dependencies.sel4-runtime-simple-static-heap]
path = "../runtime/sel4-runtime-simple-static-heap"
optional = true
