[package]
name = "sel4-runtime-phdrs"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
embedded-phdrs = []
injected-phdrs = []
tls = ["dep:sel4-reserve-tls-on-stack"]

[dependencies]
sel4-reserve-tls-on-stack = { path = "../sel4-reserve-tls-on-stack", optional = true }
zerocopy = "*"

[dependencies.unwinding]
git = "https://github.com/nspin/unwinding.git"
rev = "02b5c86f8937edbbe8bbe79fedbab374156b4134"
default-features = false
features = ["unwinder", "fde-custom", "hide-trace"]
optional = true
