[workspace]

resolver = "2"

members = [
    "crates/build-tools/render-elf-with-data",
    "crates/capdl/embed-spec",
    "crates/capdl/embedded-spec",
    "crates/capdl/embedded-spec/serialized",
    "crates/capdl/embedded-spec/validate",
    "crates/capdl/loader/core",
    "crates/capdl/loader/expecting-serialized-spec",
    "crates/capdl/loader/expecting-serialized-spec/cli/capdl-add-spec-to-loader",
    "crates/capdl/loader/with-embedded-spec",
    "crates/capdl/types",
    "crates/capdl/types/derive",
    "crates/examples/root-task/with-full-runtime",
    "crates/examples/root-task/with-minimal-runtime-with-state",
    "crates/examples/root-task/with-minimal-runtime-without-state",
    "crates/examples/sel4cp/banscii/pds/assistant",
    "crates/examples/sel4cp/banscii/pds/assistant/core",
    "crates/examples/sel4cp/banscii/pds/assistant/core/test",
    "crates/examples/sel4cp/banscii/pds/pl011-driver",
    "crates/examples/sel4cp/banscii/pds/talent",
    "crates/examples/sel4cp/banscii/pds/talent/core",
    "crates/examples/sel4cp/banscii/pds/talent/core/test",
    "crates/examples/sel4cp/hello/pds/hello",
    "crates/loader",
    "crates/loader/build-env",
    "crates/loader/config",
    "crates/loader/config/data",
    "crates/loader/config/macros",
    "crates/loader/core",
    "crates/loader/embed-aarch64-translation-tables",
    "crates/loader/payload",
    "crates/loader/payload/at-build-time",
    "crates/loader/payload/at-build-time/types",
    "crates/loader/payload/types",
    "crates/meta",
    "crates/runtime/sel4-backtrace",
    "crates/runtime/sel4-backtrace/cli/sel4-symbolize-backtrace",
    "crates/runtime/sel4-backtrace/simple",
    "crates/runtime/sel4-backtrace/types",
    "crates/runtime/sel4-dlmalloc",
    "crates/runtime/sel4-env-literal-helper",
    "crates/runtime/sel4-full-root-task-runtime",
    "crates/runtime/sel4-full-root-task-runtime/macros",
    "crates/runtime/sel4-immediate-sync-once-cell",
    "crates/runtime/sel4-logging",
    "crates/runtime/sel4-minimal-root-task-runtime",
    "crates/runtime/sel4-minimal-root-task-runtime/macros",
    "crates/runtime/sel4-panicking",
    "crates/runtime/sel4-panicking/env",
    "crates/runtime/sel4-reserve-tls-on-stack",
    "crates/runtime/sel4-runtime-phdrs",
    "crates/runtime/sel4-runtime-phdrs/cli/sel4-inject-phdrs",
    "crates/runtime/sel4-runtime-simple-entry",
    "crates/runtime/sel4-runtime-simple-static-heap",
    "crates/runtime/sel4-runtime-simple-termination",
    "crates/runtime/sel4-sync",
    "crates/sel4",
    "crates/sel4/bitfield-parser",
    "crates/sel4/bitfield-parser/test",
    "crates/sel4/bitfield-types",
    "crates/sel4/build-env",
    "crates/sel4/config",
    "crates/sel4/config/consts",
    "crates/sel4/config/data",
    "crates/sel4/config/generic/build-core",
    "crates/sel4/config/generic/macros-core",
    "crates/sel4/config/generic/types",
    "crates/sel4/config/macros",
    "crates/sel4/platform-info",
    "crates/sel4/platform-info/types",
    "crates/sel4/rustfmt-helper",
    "crates/sel4/sys",
    "crates/sel4/sys/wrappers",
    "crates/sel4cp",
    "crates/sel4cp/macros",
    "crates/support/generate-target-specs",
    "crates/tests/root-task/backtrace",
    "crates/tests/root-task/c",
    "crates/tests/root-task/config",
    "crates/tests/root-task/core-libs",
    "crates/tests/root-task/injected-phdrs",
    "crates/tests/root-task/loader",
    "crates/tests/root-task/panicking",
    "crates/tests/root-task/tls",
]
