[workspace]

resolver = "2"

members = [
    "crates/examples/root-task/with-full-runtime",
    "crates/examples/root-task/with-minimal-runtime-with-state",
    "crates/examples/root-task/with-minimal-runtime-without-state",
    "crates/loader",
    "crates/loader/build-env",
    "crates/loader/config",
    "crates/loader/config/data",
    "crates/loader/config/macros",
    "crates/loader/core",
    "crates/loader/embed-aarch64-translation-tables",
    "crates/loader/payload",
    "crates/loader/payload/at-build-time",
    "crates/loader/payload/at-build-time/types",
    "crates/loader/payload/types",
    "crates/meta/for-docs",
    "crates/runtime/sel4-backtrace",
    "crates/runtime/sel4-backtrace/cli/sel4-symbolize-backtrace",
    "crates/runtime/sel4-backtrace/types",
    "crates/runtime/sel4-dlmalloc",
    "crates/runtime/sel4-full-root-task-runtime",
    "crates/runtime/sel4-full-root-task-runtime/macros",
    "crates/runtime/sel4-immediate-sync-once-cell",
    "crates/runtime/sel4-logging",
    "crates/runtime/sel4-minimal-root-task-runtime",
    "crates/runtime/sel4-minimal-root-task-runtime/macros",
    "crates/runtime/sel4-panicking",
    "crates/runtime/sel4-runtime-building-blocks/abort",
    "crates/runtime/sel4-runtime-building-blocks/elf",
    "crates/runtime/sel4-runtime-building-blocks/injected-phdrs",
    "crates/runtime/sel4-runtime-building-blocks/injected-phdrs/cli/sel4-inject-phdrs",
    "crates/runtime/sel4-runtime-building-blocks/reserve-tls-on-stack",
    "crates/runtime/sel4-runtime-building-blocks/root-task-head",
    "crates/runtime/sel4-runtime-building-blocks/termination",
    "crates/runtime/sel4-runtime-building-blocks/unwinding-support",
    "crates/runtime/sel4-sync",
    "crates/sel4",
    "crates/sel4/bitfield-parser",
    "crates/sel4/bitfield-types",
    "crates/sel4/build-env",
    "crates/sel4/config",
    "crates/sel4/config/consts",
    "crates/sel4/config/data",
    "crates/sel4/config/generic/build-core",
    "crates/sel4/config/generic/macros-core",
    "crates/sel4/config/generic/types",
    "crates/sel4/config/macros",
    "crates/sel4/platform-info",
    "crates/sel4/platform-info/types",
    "crates/sel4/rustfmt-helper",
    "crates/sel4/sys",
    "crates/sel4/sys/wrappers",
    "crates/support/generate-target-specs",
    "crates/tests/root-task/backtrace",
    "crates/tests/root-task/config",
    "crates/tests/root-task/core-libs",
    "crates/tests/root-task/loader",
    "crates/tests/root-task/panicking",
    "crates/tests/root-task/tls",
]
