[package]
name = "sel4-async-network-mbedtls"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
futures = { version = "0.3.28", default-features = false, features = ["alloc"] }
log = "0.4.17"
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
sel4-async-network = { path = ".." }

[dependencies.mbedtls]
git = "https://github.com/nspin/rust-mbedtls"
tag = "keep/b106b115554c38559f0451a00be5de23"
default-features = false
features = ["no_std_deps", "debug"]
