[package]
name = "sel4-async-block-io"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = ["lru", "futures"]
default = ["alloc"]

[dependencies]
futures = { version = "0.3.28", default-features = false, features = ["alloc"], optional = true }
log = "0.4.17"
lru = { version = "0.10.0", optional = true }
