[package]
name = "tests-capdl-http-server-components-http-server"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
async-unsync = { version = "0.2.2", default-features = false }
futures = { version = "0.3.28", default-features = false, features = ["async-await", "alloc"] }
log = "0.4.17"
sel4 = { path = "../../../../../sel4" }
sel4-async-network = { path = "../../../../../sel4-async/network" }
sel4-async-request-statuses = { path = "../../../../../sel4-async/request-statuses" }
sel4-async-timers = { path = "../../../../../sel4-async/timers" }
sel4-bounce-buffer-allocator = { path = "../../../../../sel4-bounce-buffer-allocator" }
sel4-immediate-sync-once-cell = { path = "../../../../../sel4-immediate-sync-once-cell" }
sel4-logging = { path = "../../../../../sel4-logging" }
sel4-sync = { path = "../../../../../sel4-sync" }
sel4cp = { path = "../../../../../sel4cp", default-features = false, features = ["alloc"] }
serde = { version = "1.0.147", default-features = false, features = ["alloc", "derive"] }
tests-capdl-http-server-components-http-server-core = { path = "./core", features = [] }
tests-capdl-http-server-components-http-server-cpiofs = { path = "./cpiofs" }
tests-capdl-http-server-components-sp804-driver-core = { path = "../sp804-driver/core" }
tock-registers = "0.8.1"
virtio-drivers = { version = "0.5.0" }

[dependencies.sel4-async-single-threaded-executor]
path = "../../../../../sel4-async/single-threaded-executor"

[dependencies.sel4-externally-shared]
path = "../../../../../sel4-externally-shared"
features = ["unstable", "alloc"]

[dependencies.sel4-newlib]
path = "../../../../../sel4-newlib"
features = ["nosys", "all-symbols", "sel4-panicking-env"]

[dependencies.smoltcp]
version = "0.10.0"
default-features = false
features = [
    "alloc",
    "async",
    "medium-ethernet",
    "medium-ip",
    "medium-ieee802154",
    "proto-ipv4",
    "proto-igmp",
    "proto-dhcpv4",
    "proto-ipv6",
    "proto-dns",
    "proto-ipv4-fragmentation",
    "proto-sixlowpan-fragmentation",
    "socket-raw",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    "socket-dhcpv4",
    "socket-dns",
    "socket-mdns",
    "log"
]

[build-dependencies]
rcgen = "0.11.1"
