[package]
name = "sel4-minimal-root-task-runtime"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
default = ["state", "panic-handler"]
global-allocator = ["sel4-runtime-building-blocks-root-task-static-heap"]
panic-handler = []
state = ["sel4/state"]

[dependencies]
sel4 = { path = "../../sel4", default-features = false, features = ["single-threaded"] }
sel4-minimal-root-task-runtime-macros = { path = "./macros" }
sel4-runtime-building-blocks-termination = { path = "../sel4-runtime-building-blocks/termination" }

[dependencies.sel4-runtime-building-blocks-root-task-head]
path = "../sel4-runtime-building-blocks/root-task-head"

[dependencies.sel4-runtime-building-blocks-root-task-static-heap]
path = "../sel4-runtime-building-blocks/root-task-static-heap"
optional = true
