[package]
name = "sel4-minimal-root-task-runtime"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
default = ["state", "panic-handler"]
global-allocator = ["sel4-runtime-simple-static-heap"]
panic-handler = []
state = ["sel4/state"]

[dependencies]
sel4 = { path = "../../sel4", default-features = false, features = ["single-threaded"] }
sel4-minimal-root-task-runtime-macros = { path = "./macros" }
sel4-runtime-building-blocks-termination = { path = "../sel4-runtime-building-blocks/termination" }
sel4-runtime-simple-entry = { path = "../sel4-runtime-simple-entry" }
sel4-runtime-simple-static-heap = { path = "../sel4-runtime-simple-static-heap", optional = true }
