[package]
name = "sel4-backtrace-types"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = ["serde?/alloc"]
full = ["alloc", "serde", "postcard"]
postcard = ["serde", "dep:postcard"]
serde = ["dep:serde"]

[dependencies]
cfg-if = "*"
postcard = { version = "*", default-features = false, features = [], optional = true }
serde = { version = "*", default-features = false, features = ["derive"], optional = true }
