[package]
name = "sel4-runtime-building-blocks-root-task-static-heap"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
sel4-dlmalloc = { path = "../../sel4-dlmalloc" }
sel4-env-literal-helper = { path = "../../sel4-env-literal-helper" }
sel4-sync = { path = "../../sel4-sync" }
