[package]
name = "sel4"
version = "0.1.0"
edition = "2021"

[features]
default = ["state"]
single-threaded = []
state = []
tls = []

[dependencies]
cfg-if = "*"
sel4-config = { path = "./config" }
sel4-sys = { path = "./sys" }
