[package]
name = "render-elf-with-data"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
anyhow = "*"
clap = "3.2"
fallible-iterator = "*"
object = { version = "*", features = ["all"] }
