[package]
name = "sel4-shared-ring-buffer-smoltcp"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
log = "0.4.17"
sel4-bounce-buffer-allocator = { path = "../../sel4-bounce-buffer-allocator" }
sel4-externally-shared = { path = "../../sel4-externally-shared", features = ["unstable"] }
sel4-shared-ring-buffer = { path = ".." }

[dependencies.smoltcp]
version = "0.10.0"
default-features = false
features = [
    "alloc",
    "async",
    "medium-ethernet",
    "medium-ip",
    "medium-ieee802154",
    "proto-ipv4",
    "proto-igmp",
    "proto-dhcpv4",
    "proto-ipv6",
    "proto-dns",
    "proto-ipv4-fragmentation",
    "proto-sixlowpan-fragmentation",
    "socket-raw",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    "socket-dhcpv4",
    "socket-dns",
    "socket-mdns",
    "log"
]
