[package]
name = "capdl-loader-with-embedded-spec"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
deflate = ["capdl-embedded-spec/deflate"]

[dependencies]
capdl-embedded-spec = { path = "../../embedded-spec" }
capdl-loader-core = { path = "../core" }
capdl-types = { path = "../../types" }
sel4 = { path = "../../../sel4" }
sel4-logging = { path = "../../../runtime/sel4-logging" }
sel4-minimal-root-task-runtime = { path = "../../../runtime/sel4-minimal-root-task-runtime" }

[build-dependencies]
capdl-embedded-spec-validate = { path = "../../embedded-spec/validate" }
