[package]
name = "capdl-loader-with-embedded-spec"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
deflate = [
    "capdl-loader-with-embedded-spec-embedded-spec/deflate",
    "capdl-loader-with-embedded-spec-embedded-spec-validate/deflate"
]

[dependencies]
capdl-loader-core = { path = "../core" }
capdl-loader-with-embedded-spec-embedded-spec = { path = "./embedded-spec" }
capdl-types = { path = "../../types" }
sel4 = { path = "../../../sel4" }
sel4-logging = { path = "../../../sel4-logging" }

[dependencies.sel4-root-task]
path = "../../../sel4-root-task"
default-features = false
features = ["single-threaded"]

[build-dependencies]
capdl-loader-with-embedded-spec-embedded-spec-validate = { path = "./embedded-spec/validate" }
