[package]
name = "sel4-backtrace"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]

[features]
alloc = ["sel4-backtrace-types/alloc"]
full = ["alloc", "postcard", "unwinding"]
postcard = ["sel4-backtrace-types/postcard", "dep:postcard", "dep:serde"]
unwinding = ["dep:unwinding"]

[dependencies]
cfg-if = "*"
postcard = { version = "*", default-features = false, features = [], optional = true }
serde = { version = "*", default-features = false, features = [], optional = true }
sel4-backtrace-types = { path = "./types" }
unwinding = { path = "../../../../more-external/unwinding", default-features = false, features = ["unwinder", "fde-custom", "hide-trace"], optional = true }
