[package]
name = "sel4-backtrace"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
alloc = ["sel4-backtrace-types/alloc"]
full = ["alloc", "postcard", "unwinding"]
postcard = ["sel4-backtrace-types/postcard", "dep:postcard", "dep:serde"]
unwinding = ["dep:unwinding"]

[dependencies]
cfg-if = "*"
postcard = { version = "*", default-features = false, features = [], optional = true }
sel4-backtrace-types = { path = "./types" }
serde = { version = "*", default-features = false, features = [], optional = true }

[dependencies.unwinding]
git = "https://github.com/nspin/unwinding.git"
rev = "75c9607b61418e49cb5059eabb782c13c3ae4b6b"
default-features = false
features = ["unwinder", "fde-custom", "hide-trace"]
optional = true
