[package]
name = "loader-payload-at-build-time-types"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
loader-payload-types = { path = "../../types", features = ["serde"] }
serde = { version = "1.0.147", default-features = false, features = ["derive", "alloc"] }
