[package]
name = "capdl-initializer-core"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
capdl-types = { path = "../../types", features = ["sel4"] }
log = "0.4.17"
sel4 = { path = "../../../sel4" }
