[package]
name = "sel4cp-postcard"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
postcard = { version = "*", default-features = false, features = [] }
sel4 = { path = "../../sel4" }
sel4cp = { path = ".." }
serde = { version = "*", default-features = false, features = [] }
