[package]
name = "loader-config-macros"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[lib]
proc-macro = true

[dependencies]
loader-config-data = { path = "../data" }
sel4-config-generic-macros-core = { path = "../../../sel4/config/generic/macros-core" }
sel4-config-generic-types = { path = "../../../sel4/config/generic/types" }
