[package]
name = "sel4-config-generic-types"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]

[dependencies]
serde = { version = "*", default-features = false, features = ["alloc", "derive"], optional = true }
