[package]
name = "capdl-loader-expecting-serialized-spec"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
capdl-loader-core = { path = "../core" }
capdl-loader-expecting-serialized-spec-types = { path = "./types" }
capdl-types = { path = "../../types", features = ["alloc", "serde", "deflate"] }
log = "*"
postcard = { version = "*", default-features = false, features = ["alloc"] }
sel4 = { path = "../../../sel4" }
sel4-logging = { path = "../../../runtime/sel4-logging" }

[dependencies.sel4-root-task-runtime]
path = "../../../runtime/sel4-root-task-runtime"
default-features = false
features = ["global-allocator", "single-threaded"]
