[package]
name = "capdl-loader-expecting-serialized-spec"
version = "0.1.0"
edition = "2021"

[dependencies]
capdl-loader-core = { path = "../core" }
capdl-types = { path = "../../types", features = ["alloc", "serde", "deflate"] }
log = "*"
postcard = { version = "*", default-features = false, features = ["alloc"] }
sel4 = { path = "../../../sel4" }
sel4-logging = { path = "../../../runtime/sel4-logging" }

[dependencies.sel4-full-root-task-runtime]
path = "../../../runtime/sel4-full-root-task-runtime"
features = ["full"]
