[package]
name = "sel4-runtime-phdrs"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
embedded-phdrs = []
tls = ["dep:sel4-reserve-tls-on-stack"]

[dependencies]
sel4-reserve-tls-on-stack = { path = "../sel4-reserve-tls-on-stack", optional = true }

[dependencies.unwinding]
version = "0.1.6"
default-features = false
features = ["unwinder", "fde-custom", "hide-trace"]
optional = true
