[package]
name = "loader-build-env"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
sel4-build-env = { path = "../../sel4/build-env" }
