[package]
name = "capdl-initializer-add-spec"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
anyhow = "1.0.66"
capdl-initializer-types = { path = "../types" }
capdl-types = { path = "../../types", features = ["alloc", "serde", "deflate"] }
clap = "3.2.23"
fallible-iterator = "0.2.0"
object = { version = "0.31.0", features = ["all"] }
postcard = { version = "1.0.2", default-features = false, features = ["alloc"] }
sel4-render-elf-with-data = { path = "../../../sel4-render-elf-with-data" }
serde_json = "1.0.87"
