[package]
name = "sel4-symbolize-backtrace"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "MIT"

[dependencies]
addr2line = "0"
clap = "3"
fallible-iterator = "0"
gimli = "0"
hex = "0"
memmap = "0"
object = "0"
postcard = { version = "*", default-features = false, features = ["alloc"] }
sel4-backtrace-types = { path = "../../types", features = ["full"] }
