[package]
name = "sel4-runtime-phdrs-injected"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
sel4-runtime-phdrs = { path = ".." }
