[package]
name = "banscii-talent-core"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
log = "*"
rsa = { version = "0.8.1", default-features = false, features = ["pem"] }
