[package]
name = "loader-payload-types"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
heapless = { version = "*", features = ["serde"] }
serde = { version = "*", default-features = false, features = ["derive"], optional = true }
