[package]
name = "meta-for-docs"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
full-root-task-runtime = ["dep:sel4-full-root-task-runtime"]
minimal-root-task-runtime = ["dep:sel4-minimal-root-task-runtime"]

[dependencies]
sel4 = { path = "../../sel4" }
sel4-config = { path = "../../sel4/config" }
sel4-logging = { path = "../../runtime/sel4-logging" }
sel4-platform-info = { path = "../../sel4/platform-info" }
sel4-sync = { path = "../../runtime/sel4-sync" }
sel4-sys = { path = "../../sel4/sys" }

[dependencies.sel4-full-root-task-runtime]
path = "../../runtime/sel4-full-root-task-runtime"
features = ["full"]
optional = true

[dependencies.sel4-minimal-root-task-runtime]
path = "../../runtime/sel4-minimal-root-task-runtime"
optional = true
