[package]
name = "meta"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
root-task = ["sel4-root-task-runtime"]
sel4cp = ["dep:sel4cp", "sel4cp-postcard"]

[dependencies]
capdl-types = { path = "../../capdl/types", features = ["alloc"] }
cfg-if = "1.0.0"
log = "0.4.17"

[target."cfg(all(target_env = \"sel4\", not(target_arch = \"x86_64\")))".dependencies]
sel4-platform-info = { path = "../../sel4/platform-info", optional = true }

[target."cfg(not(target_os = \"none\"))".dependencies]
sel4-render-elf-with-data = { path = "../../build-tools/sel4-render-elf-with-data" }

[target."cfg(target_env = \"sel4\")".dependencies]
sel4 = { path = "../../sel4" }
sel4-backtrace = { path = "../../runtime/sel4-backtrace", features = ["full"] }
sel4-backtrace-embedded-debug-info = { path = "../../runtime/sel4-backtrace/embedded-debug-info" }
sel4-backtrace-simple = { path = "../../runtime/sel4-backtrace/simple", features = ["alloc"] }
sel4-backtrace-types = { path = "../../runtime/sel4-backtrace/types", features = ["full"] }
sel4-config = { path = "../../sel4/config" }
sel4-logging = { path = "../../runtime/sel4-logging" }
sel4-sync = { path = "../../runtime/sel4-sync" }
sel4-sys = { path = "../../sel4/sys" }
sel4cp = { path = "../../sel4cp", features = ["full"], optional = true }
sel4cp-postcard = { path = "../../sel4cp/postcard", optional = true }

[target."cfg(target_env = \"sel4\")".dependencies.sel4-root-task-runtime]
path = "../../runtime/sel4-root-task-runtime"
features = ["full"]
optional = true
