[package]
name = "sel4-simple-task-config-types"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
cfg-if = "*"
serde = { version = "*", default-features = false, features = ["derive"] }

[target."cfg(target_env = \"sel4\")".dependencies]
sel4 = { path = "../../sel4" }
sel4-simple-task-threading = { path = "../sel4-simple-task-threading" }
