[package]
name = "capdl-embedded-spec-validate"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[features]
deflate = ["capdl-embedded-spec/deflate"]

[dependencies]
capdl-embedded-spec = { path = ".." }
capdl-loader-with-embedded-spec-build-env = { path = "../../loader/with-embedded-spec/build-env" }
capdl-types = { path = "../../types" }
