[package]
name = "capdl-embedded-spec-validate"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
capdl-embedded-spec = { path = ".." }
capdl-embedded-spec-serialized = { path = "../serialized" }
capdl-types = { path = "../../types" }
