[package]
name = "sel4-reserve-tls-on-stack"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
cfg-if = "*"
sel4-runtime-building-blocks-elf = { path = "../sel4-runtime-building-blocks/elf" }
