name: "Check"
on:
  pull_request:
  workflow_dispatch:
jobs:
  check-everything:
    name: Check everything
    runs-on: ubuntu-latest
    steps:
      - name: Prepare to maximize build space
        run: sudo mkdir /nix
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /nix
          root-reserve-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run checks
        run: make -C hacking/ci/github-actions check
