[package]
name = "loader-payload-at-build-time"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
loader-payload-at-build-time-types = { path = "./types" }
serde_json = "1.0.87"

[build-dependencies]
loader-build-env = { path = "../../build-env" }
loader-payload-at-build-time-types = { path = "./types" }
object = "0.30.3"
quote = "1.0.23"
sel4-config = { path = "../../../sel4/config" }
sel4-platform-info = { path = "../../../sel4/platform-info" }
serde_json = "1.0.87"
